export const accountSectionsConfig = {
  "Contact Info": {
    component: "ContactInfo",
    apiEndpoint: "profile",
    method: "GET",
    updateEndpoint: "profile",
    updateMethod: "PATCH",
    fields: [
      { name: "firstName", type: "text", label: "First Name", required: true },
      { name: "lastName", type: "text", label: "Last Name", required: true },
      { name: "email", type: "email", label: "Email Address", required: true },
      { name: "phone", type: "tel", label: "Phone Number", required: false },
    ],
    sectionType: "form",
  },
  "Credit/Debit Cards": {
    component: "PaymentMethods",
    apiEndpoint: "payment-methods",
    method: "GET",
    updateEndpoint: "payment-methods",
    sectionType: "list",
    canAdd: true,
    canEdit: true,
    canDelete: true,
  },
  "Linked Accounts": {
    component: "LinkedAccounts",
    apiEndpoint: "linked-accounts",
    method: "GET",
    sectionType: "connection",
    providers: ["google", "facebook", "apple"],
  },
  "Communication Preferences": {
    component: "CommunicationPrefs",
    apiEndpoint: "communication-preferences",
    method: "GET",
    updateEndpoint: "communication-preferences",
    updateMethod: "PATCH",
    sectionType: "preferences",
    categories: ["email", "sms", "push"],
  },
  "Close Account": {
    component: "CloseAccount",
    apiEndpoint: "account",
    updateEndpoint: "account",
    updateMethod: "DELETE",
    sectionType: "destructive",
    requiresConfirmation: true,
    confirmationText: "Are you sure you want to permanently delete your account? This action cannot be undone.",
  },
};